-- ============================================================
-- Disable Row Level Security on all tables
-- Run this in Supabase SQL Editor if you're getting permission errors
-- ============================================================

ALTER TABLE IF EXISTS stakes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS wards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS callings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calling_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calling_workflow_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS calling_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS leadership_positions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meetings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meeting_agendas DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS meeting_minutes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS standard_meeting_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS welfare_cases DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS self_reliance_participants DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS missionary_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS full_time_missionaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS convert_integration DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS temple_attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS family_history_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS temple_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS youth_programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS priesthood_advancements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS youth_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_modules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS training_completions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS handbook_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS policy_updates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS interviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS special_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_speakers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS event_music DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- DONE! RLS disabled on all tables.
-- ============================================================
