-- Sync 2026 stake calendar from Google Sheet tabs + business rules
-- Generated by scripts/generate-2026-calendar-migration.mjs — re-run script after sheet edits.
-- Ward-specific sacrament/teaching times: apply 054_calendar_sunday_ward_times.sql (do not re-run this file after 054).

DELETE FROM meeting_agendas WHERE meeting_id IN (
  SELECT id FROM meetings WHERE source_type IN ('visit_schedule', 'thursday_schedule', 'council_prep')
);
DELETE FROM meetings WHERE source_type IN ('visit_schedule', 'thursday_schedule', 'council_prep');

DELETE FROM presidency_visit_schedule WHERE stake_id = (SELECT id FROM stakes LIMIT 1);
DELETE FROM thursday_schedule WHERE stake_id = (SELECT id FROM stakes LIMIT 1);

INSERT INTO presidency_visit_schedule (stake_id, visit_date, week_number, president_assignment, first_counselor_assignment, second_counselor_assignment, entry_type, notes)
SELECT s.id, d.visit_date::date, d.week_number, d.president_assignment, d.first_counselor_assignment, d.second_counselor_assignment, d.entry_type, d.notes
FROM (SELECT id FROM stakes LIMIT 1) AS s
CROSS JOIN (
  VALUES
    ('2026-01-04'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-01-04'::date, 1::int, '18th', '12th', 'Cache Valley baby blessing', 'visit'::text, NULL),
    ('2026-01-11'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-01-11'::date, 2::int, '8th Ward
  Teach Relief Society', '17th Ward
  Teach Youth', '17th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-01-18'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-01-18'::date, 3::int, '23rd', '22nd out of town', '19th', 'visit'::text, NULL),
    ('2026-01-25'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-01-25'::date, 4::int, '8th Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 12:00 PM'),
    ('2026-02-01'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-02-01'::date, 1::int, '19th', '18th PC Out of Town', '17th', 'visit'::text, NULL),
    ('2026-02-08'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-02-08'::date, 2::int, '12th Ward
  Teach Relief Society', '17th Ward
  Teach Youth', '18th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-02-15'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-02-15'::date, 3::int, '18th', '12th', '22nd', 'visit'::text, NULL),
    ('2026-02-22'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-02-22'::date, 4::int, '18th Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 10:30 AM'),
    ('2026-03-01'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-03-01'::date, 1::int, '17th', '12th', '8th', 'visit'::text, NULL),
    ('2026-03-08'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-03-08'::date, 2::int, '18th Ward
  Teach Relief Society', '18th Ward
  Teach Youth', '19th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-03-15'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-03-15'::date, 3::int, '12th', '8th', '23rd', 'visit'::text, NULL),
    ('2026-03-22'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-03-22'::date, 4::int, '19th Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 9:00 AM'),
    ('2026-03-29'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-03-29'::date, 5::int, '8th', '12th', '22nd', 'visit'::text, NULL),
    ('2026-04-05'::date, 1::int, 'General Conference', NULL, NULL, 'general_conference'::text, NULL),
    ('2026-04-12'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-04-12'::date, 2::int, '17th Ward
  Teach Relief Society', '19th Ward
  Teach Youth', '22nd Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-04-19'::date, 3::int, 'Stake Conference', NULL, NULL, 'stake_conference'::text, NULL),
    ('2026-04-26'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-04-26'::date, 4::int, '19th Ward
  Teach Relief Society', '22nd Ward
  Teach Youth', '23rd Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-05-03'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-05-03'::date, 1::int, '17th', '18th', '19th', 'visit'::text, NULL),
    ('2026-05-10'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-05-10'::date, 2::int, '22nd Ward
  Teach Relief Society', '23rd Ward
  Teach Youth', '8th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-05-17'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-05-17'::date, 3::int, '18th', '19th', '17th', 'visit'::text, NULL),
    ('2026-05-24'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-05-24'::date, 4::int, '8th Ward
  Teach Elder''s Quorum', '12th Ward
  Teach Youth', '17th Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-05-31'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-05-31'::date, 5::int, '19th', '17th', '22nd', 'visit'::text, NULL),
    ('2026-06-07'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-06-07'::date, 1::int, '22nd', '12th', '23rd', 'visit'::text, NULL),
    ('2026-06-14'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-06-14'::date, 2::int, '23rd Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 9:00 AM'),
    ('2026-06-21'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-06-21'::date, 3::int, '23rd', '8th', '12th', 'visit'::text, NULL),
    ('2026-06-28'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-06-28'::date, 4::int, '12th Ward
  Teach Elder''s Quorum', '8th Ward
  Teach Youth', '18th Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-07-05'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-07-05'::date, 1::int, '18th', '22nd', '8th', 'visit'::text, NULL),
    ('2026-07-12'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-07-12'::date, 2::int, '17th Ward
  Teach Elder''s Quorum', '18th Ward
  Teach Youth', '19th Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-07-19'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-07-19'::date, 3::int, '18th', '12th', '12th', 'visit'::text, NULL),
    ('2026-07-26'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-07-26'::date, 4::int, '18th Ward
  Teach Elder''s Quorum', '19th Ward
  Teach Youth', '22nd Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-08-02'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-08-02'::date, 1::int, '19th', '22nd', '23', 'visit'::text, NULL),
    ('2026-08-09'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-08-09'::date, 2::int, '17th Ward
  Teach Relief Society', '12th Ward
  Teach Youth', '17th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-08-16'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-08-16'::date, 3::int, '22nd', '23rd', '8th', 'visit'::text, NULL),
    ('2026-08-23'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-08-23'::date, 4::int, '17th Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 9:00 AM'),
    ('2026-08-30'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-08-30'::date, 5::int, '18th', '12th', '22nd', 'visit'::text, NULL),
    ('2026-09-06'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-09-06'::date, 1::int, '12th', '22nd', '8th', 'visit'::text, NULL),
    ('2026-09-13'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-09-13'::date, 2::int, '22nd Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 1:30 PM'),
    ('2026-09-20'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-09-20'::date, 3::int, '23rd', '8th', '12th', 'visit'::text, NULL),
    ('2026-09-27'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-09-27'::date, 4::int, '19th Ward
  Teach Elder''s Quorum', '22nd Ward
  Teach Youth', '23rd Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-10-04'::date, 1::int, 'GENERAL CONFERENCE', NULL, NULL, 'general_conference'::text, NULL),
    ('2026-10-11'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-10-11'::date, 2::int, '22nd Ward
  Teach Elder''s Quorum', '23rd Ward
  Teach Youth', '8th Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-10-18'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-10-18'::date, 3::int, '8th', '12th', '17th', 'visit'::text, NULL),
    ('2026-10-25'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-10-25'::date, 4::int, '23rd Ward
  Teach Elder''s Quorum', '8th Ward
  Teach Youth', '12th Ward
  Teach Relief Society', 'teaching'::text, NULL),
    ('2026-11-01'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-11-01'::date, 1::int, '17th', '18th', '19th', 'visit'::text, NULL),
    ('2026-11-08'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-11-08'::date, 2::int, '12th Ward Conference', NULL, NULL, 'ward_conference'::text, 'Conference time: 12:00 PM'),
    ('2026-11-15'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-11-15'::date, 3::int, '12th', '17th', '18th', 'visit'::text, NULL),
    ('2026-11-22'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-11-22'::date, 4::int, '8th Ward
  Teach Relief Society', '17th Ward
  Teach Youth', '19th Ward
  Teach Elder''s Quorum', 'teaching'::text, NULL),
    ('2026-11-29'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-11-29'::date, 5::int, '19th', '22nd', '23rd', 'visit'::text, NULL),
    ('2026-12-06'::date, 1::int, 'Stake Conference', NULL, NULL, 'stake_conference'::text, NULL),
    ('2026-12-13'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-12-13'::date, 2::int, '8th', '17th', '19th', 'visit'::text, NULL),
    ('2026-12-20'::date, NULL::int, NULL, NULL, NULL, 'stake_council_meeting'::text, NULL),
    ('2026-12-20'::date, 3::int, '18th', '12th', '22nd', 'visit'::text, NULL),
    ('2026-12-27'::date, NULL::int, NULL, NULL, NULL, 'high_council_meeting'::text, NULL),
    ('2026-12-27'::date, 4::int, '22nd', '23rd', '8th', 'visit'::text, NULL)
) AS d(visit_date, week_number, president_assignment, first_counselor_assignment, second_counselor_assignment, entry_type, notes);

INSERT INTO thursday_schedule (stake_id, visit_date, ward, meeting_type, start_time, end_time, slot, pg_attendee, pc_attendee, pw_attendee, notes)
SELECT s.id, t.visit_date::date, t.ward, t.meeting_type, t.start_time, t.end_time, t.slot, t.pg_attendee, t.pc_attendee, t.pw_attendee, t.notes
FROM (SELECT id FROM stakes LIMIT 1) AS s
CROSS JOIN (
  VALUES
    ('2026-04-23'::date, '22nd Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, 'Clyde Burton', NULL, 'Michael Dyer', 'Rick Smith'),
    ('2026-04-23'::date, '23rd Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, 'Chris Herrod', NULL, NULL, 'Kent Jensen is covering'),
    ('2026-04-30'::date, 'Coordinating Council', 'Coordinating Council', '6:00 PM', '10:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-05-07'::date, '18th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-05-07'::date, 'Bishops Council', 'Bishops Council', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-05-14'::date, '19th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-05-14'::date, 'Elders Quorum Council', 'Elders Quorum Presidents', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-05-21'::date, 'Relief Society Council', 'Relief Society Presidents', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-05-28'::date, '8th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-05-28'::date, '12th Ward', 'Elders Quorum Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-06-04'::date, '17th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-06-04'::date, '19th Ward', 'Elders Quorum Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-06-11'::date, '18th Ward Blitz', 'Elders Quorum Ministering', '6:30 PM', NULL, NULL::int, NULL, NULL, NULL, NULL),
    ('2026-06-25'::date, '22nd Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-06-25'::date, '23rd Ward', 'Elders Quorum Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-07-02'::date, '8th Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-07-02'::date, '12th Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-07-09'::date, '17th Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-07-09'::date, '18th Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-07-16'::date, '19th Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-07-16'::date, '22nd Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-07-23'::date, '23rd Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-07-23'::date, '8th Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-07-30'::date, '12th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-07-30'::date, '17th Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-08-06'::date, '18th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-08-06'::date, '19th Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-08-13'::date, '22nd Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-08-13'::date, '23rd Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-08-20'::date, '17th Ward Blitz', 'Elders Quorum Ministering', '6:30 PM', NULL, NULL::int, NULL, NULL, NULL, NULL),
    ('2026-08-20'::date, 'Coordinating Council', 'Coordinating Council', '6:00 PM', '10:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-08-27'::date, '8th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-08-27'::date, 'Bishops Council', 'Bishops Council', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-09-03'::date, '12th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-09-03'::date, 'Elders Quorum Council', 'Elders Quorum Presidents', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-09-10'::date, '22nd Ward Blitz', 'Elders Quorum Ministering', '6:30 PM', NULL, NULL::int, NULL, NULL, NULL, NULL),
    ('2026-09-24'::date, '18th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-09-24'::date, 'Relief Society Council', 'Relief Society Presidents', '7:00 PM', '8:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-10-01'::date, '19th Ward', 'Elders Quorum Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-10-01'::date, '8th Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-10-08'::date, '12th Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-10-08'::date, '17th Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-10-15'::date, '18th Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-10-15'::date, '19th Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-10-22'::date, '22nd Ward', 'Relief Society Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-10-22'::date, '23rd Ward', 'Relief Society Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-10-29'::date, 'Coordinating Council', 'Coordinating Council', '6:00 PM', '10:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-11-05'::date, '23rd Ward Blitz', 'Elders Quorum Ministering', '6:30 PM', NULL, NULL::int, NULL, NULL, NULL, NULL),
    ('2026-11-12'::date, '8th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-11-12'::date, 'Bishops Council', 'Bishops Council', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-11-19'::date, '12th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-11-19'::date, 'Elders Quorum Council', 'Elders Quorum Presidents', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-12-03'::date, '17th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-12-03'::date, 'Relief Society Council', 'Relief Society Presidents', '7:00 PM', '9:00 PM', NULL::int, NULL, NULL, NULL, NULL),
    ('2026-12-10'::date, '18th Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-12-10'::date, '19th Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL),
    ('2026-12-17'::date, '22nd Ward', 'Bishopric Ministering', '6:00 PM', '6:45 PM', 1, NULL, NULL, NULL, NULL),
    ('2026-12-17'::date, '23rd Ward', 'Bishopric Ministering', '7:00 PM', '7:45 PM', 2, NULL, NULL, NULL, NULL)
) AS t(visit_date, ward, meeting_type, start_time, end_time, slot, pg_attendee, pc_attendee, pw_attendee, notes);

DO $$
DECLARE
  v_stake_id UUID;
  rec RECORD;
  v_meeting_id UUID;
  v_title TEXT;
  v_color TEXT;
  v_type TEXT;
  v_order INT;
  v_scheduled TIMESTAMPTZ;
BEGIN
  SELECT id INTO v_stake_id FROM stakes LIMIT 1;
  FOR rec IN SELECT * FROM presidency_visit_schedule ORDER BY visit_date, entry_type
  LOOP
    CASE rec.entry_type
      WHEN 'visit' THEN v_title := 'Sunday Ward Visits'; v_color := '#0891b2'; v_type := 'ward_visit';
      WHEN 'teaching' THEN v_title := 'Sunday Teaching Assignments'; v_color := '#7c3aed'; v_type := 'teaching';
      WHEN 'ward_conference' THEN v_title := rec.president_assignment; v_color := '#d97706'; v_type := 'ward_conference';
      WHEN 'stake_conference' THEN v_title := 'Stake Conference'; v_color := '#dc2626'; v_type := 'stake_conference';
      WHEN 'general_conference' THEN v_title := 'General Conference'; v_color := '#16a34a'; v_type := 'general_conference';
      WHEN 'high_council_meeting' THEN v_title := 'High Council Meeting'; v_color := '#6b7280'; v_type := 'high_council';
      WHEN 'stake_council_meeting' THEN v_title := 'Stake Council Meeting'; v_color := '#6b7280'; v_type := 'stake_council';
      ELSE v_title := 'Presidency Schedule'; v_color := '#3b82f6'; v_type := 'other';
    END CASE;
    v_scheduled := CASE rec.entry_type
      WHEN 'high_council_meeting' THEN (rec.visit_date::timestamp + interval '6 hours') AT TIME ZONE 'America/Denver'
      ELSE (rec.visit_date::timestamp + interval '9 hours') AT TIME ZONE 'America/Denver'
    END;
    INSERT INTO meetings (stake_id, title, meeting_type, scheduled_date, description, color, source_type, viewable_by_roles)
    VALUES (
      v_stake_id, v_title, v_type, v_scheduled,
      CASE WHEN rec.notes IS NOT NULL THEN rec.notes ELSE NULL END,
      v_color, 'visit_schedule', ARRAY['stake_presidency']::text[]
    ) RETURNING id INTO v_meeting_id;
    IF rec.entry_type IN ('visit', 'teaching') THEN
      v_order := 1;
      IF rec.president_assignment IS NOT NULL THEN
        INSERT INTO meeting_agendas (meeting_id, item_order, title, presenter)
        VALUES (v_meeting_id, v_order, 'President Garrett — ' || rec.president_assignment, 'President Garrett');
        v_order := v_order + 1;
      END IF;
      IF rec.first_counselor_assignment IS NOT NULL THEN
        INSERT INTO meeting_agendas (meeting_id, item_order, title, presenter)
        VALUES (v_meeting_id, v_order, 'President Chandler — ' || rec.first_counselor_assignment, 'President Chandler');
        v_order := v_order + 1;
      END IF;
      IF rec.second_counselor_assignment IS NOT NULL THEN
        INSERT INTO meeting_agendas (meeting_id, item_order, title, presenter)
        VALUES (v_meeting_id, v_order, 'President Williams — ' || rec.second_counselor_assignment, 'President Williams');
        v_order := v_order + 1;
      END IF;
    END IF;
  END LOOP;
END $$;

DO $$
DECLARE
  v_stake_id UUID;
  rec RECORD;
  v_meeting_id UUID;
  v_scheduled TIMESTAMPTZ;
  v_title TEXT;
  v_color TEXT;
  v_desc TEXT;
BEGIN
  SELECT id INTO v_stake_id FROM stakes LIMIT 1;
  FOR rec IN SELECT * FROM thursday_schedule ORDER BY visit_date, start_time NULLS LAST, ward
  LOOP
    IF rec.start_time IS NOT NULL THEN
      v_scheduled := to_timestamp(to_char(rec.visit_date, 'YYYY-MM-DD') || ' ' || rec.start_time, 'YYYY-MM-DD HH12:MI AM') AT TIME ZONE 'America/Denver';
    ELSE
      v_scheduled := (rec.visit_date::timestamp + interval '18 hours 30 minutes') AT TIME ZONE 'America/Denver';
    END IF;
    v_title := rec.ward || ' — ' ||
      CASE
        WHEN rec.meeting_type = 'Relief Society Ministering' THEN 'RS Ministering'
        WHEN rec.meeting_type = 'Relief Society Presidents' THEN 'RS Presidents Council'
        WHEN rec.meeting_type = 'Elders Quorum Ministering' THEN 'EQ Ministering'
        WHEN rec.meeting_type = 'Elders Quorum Presidents' THEN 'EQ Presidents Council'
        WHEN rec.meeting_type = 'Bishopric Ministering' THEN 'Bishopric Ministering'
        ELSE rec.meeting_type
      END;
    v_desc := COALESCE(rec.start_time || COALESCE(' - ' || rec.end_time, ''), '');
    IF rec.pg_attendee IS NOT NULL OR rec.pc_attendee IS NOT NULL OR rec.pw_attendee IS NOT NULL THEN
      v_desc := v_desc || E'\nPG: ' || COALESCE(rec.pg_attendee, '—') || ' | PC: ' || COALESCE(rec.pc_attendee, '—') || ' | PW: ' || COALESCE(rec.pw_attendee, '—');
    END IF;
    IF rec.notes IS NOT NULL THEN v_desc := v_desc || E'\n' || rec.notes; END IF;
    IF rec.meeting_type = 'Coordinating Council' OR rec.meeting_type = 'Bishops Council' THEN v_color := '#6b7280';
    ELSIF rec.meeting_type LIKE '%Elders Quorum%' OR rec.meeting_type = 'Elders Quorum Presidents' THEN v_color := '#2563eb';
    ELSIF rec.meeting_type LIKE '%Relief Society%' OR rec.meeting_type = 'Relief Society Presidents' THEN v_color := '#dc2626';
    ELSE v_color := '#0d9488';
    END IF;
    INSERT INTO meetings (stake_id, title, meeting_type, scheduled_date, description, color, source_type, viewable_by_roles)
    VALUES (
      v_stake_id, v_title,
      CASE
        WHEN rec.meeting_type LIKE 'Bishopric%' THEN 'bishopric_ministering'
        WHEN rec.meeting_type LIKE 'Elders Quorum%' OR rec.meeting_type = 'Elders Quorum Presidents' THEN 'eq_ministering'
        WHEN rec.meeting_type LIKE 'Relief Society%' OR rec.meeting_type = 'Relief Society Presidents' THEN 'rs_ministering'
        WHEN rec.meeting_type = 'Coordinating Council' THEN 'coordinating_council'
        WHEN rec.meeting_type = 'Bishops Council' THEN 'bishops_council'
        ELSE 'thursday_ministering'
      END,
      v_scheduled, v_desc, v_color, 'thursday_schedule', ARRAY['stake_presidency', 'stake_council']::text[]
    ) RETURNING id INTO v_meeting_id;
    INSERT INTO meeting_agendas (meeting_id, item_order, title, presenter, description)
    VALUES (v_meeting_id, 1, rec.ward || ' — ' || rec.meeting_type, NULL,
      COALESCE(rec.start_time || COALESCE(' - ' || rec.end_time, ''), '') ||
      CASE WHEN rec.pg_attendee IS NOT NULL THEN E'\nPG: ' || rec.pg_attendee ELSE '' END ||
      CASE WHEN rec.pc_attendee IS NOT NULL THEN E'\nPC: ' || rec.pc_attendee ELSE '' END ||
      CASE WHEN rec.pw_attendee IS NOT NULL THEN E'\nPW: ' || rec.pw_attendee ELSE '' END ||
      CASE WHEN rec.notes IS NOT NULL THEN E'\nNote: ' || rec.notes ELSE '' END);
  END LOOP;
END $$;

INSERT INTO meetings (stake_id, title, meeting_type, scheduled_date, description, color, source_type, viewable_by_roles)
SELECT
  s.id,
  'Stake Presidency Meeting',
  'stake_presidency',
  (d.prep_date::timestamp + interval '19 hours 30 minutes') AT TIME ZONE 'America/Denver',
  'Preparation for Thursday coordinating / bishops / elders quorum / relief society council (7:30 PM).',
  '#3b82f6',
  'council_prep',
  ARRAY['stake_presidency']::text[]
FROM (SELECT id FROM stakes LIMIT 1) AS s
CROSS JOIN (
  VALUES
    ('2026-04-29'::date),
    ('2026-05-06'::date),
    ('2026-05-13'::date),
    ('2026-05-20'::date),
    ('2026-08-19'::date),
    ('2026-08-26'::date),
    ('2026-09-02'::date),
    ('2026-09-23'::date),
    ('2026-10-28'::date),
    ('2026-11-11'::date),
    ('2026-11-18'::date),
    ('2026-12-02'::date)
) AS d(prep_date);
