-- 062_meeting_agendas_text_columns.sql
--
-- Schema/code mismatch fix.
--
-- The meeting agenda UI (and the in-app handbook templates) treat the
-- `assigned_to` column as a free-text name (e.g. "Brother Smith") and
-- also write to a `presenter` column that earlier migrations already
-- INSERT into. The original 003_meetings_module.sql, however, defined
-- `assigned_to` as `UUID REFERENCES users(id)` and never created
-- `presenter` at all.
--
-- That mismatch caused autosave to fail with:
--   ERROR: invalid input syntax for type uuid: "test"
--
-- This migration realigns the schema with what the application actually
-- writes:
--   1. Drop the FK to users(id).
--   2. Convert `assigned_to` to TEXT (preserving any existing values by
--      casting their UUID textual form).
--   3. Add a `presenter` TEXT column if it doesn't already exist.
--
-- Idempotent: safe to run multiple times.

-- 1. Drop FK constraint to users(id) if it exists. The constraint name in
-- the original migration was generated by Postgres; look it up dynamically.
DO $$
DECLARE
  fk_name TEXT;
BEGIN
  SELECT tc.constraint_name INTO fk_name
  FROM information_schema.table_constraints tc
  JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.table_schema = kcu.table_schema
  WHERE tc.table_schema = 'public'
    AND tc.table_name = 'meeting_agendas'
    AND tc.constraint_type = 'FOREIGN KEY'
    AND kcu.column_name = 'assigned_to'
  LIMIT 1;

  IF fk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.meeting_agendas DROP CONSTRAINT %I', fk_name);
  END IF;
END $$;

-- 2. Convert `assigned_to` from UUID to TEXT. The USING cast keeps any
-- legacy UUID values around as their textual representation so no data is
-- lost. If the column is already TEXT this is a no-op.
DO $$
DECLARE
  current_type TEXT;
BEGIN
  SELECT data_type INTO current_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'meeting_agendas'
    AND column_name = 'assigned_to';

  IF current_type IS DISTINCT FROM 'text' THEN
    ALTER TABLE public.meeting_agendas
      ALTER COLUMN assigned_to TYPE TEXT USING assigned_to::text;
  END IF;
END $$;

-- 3. Add presenter column if it isn't already there.
ALTER TABLE public.meeting_agendas
  ADD COLUMN IF NOT EXISTS presenter TEXT;

COMMENT ON COLUMN public.meeting_agendas.assigned_to IS
  'Free-text name of the person assigned to this agenda item (e.g. "Brother Smith"). '
  'Used by the in-app handbook templates. Was originally a UUID reference to '
  'users(id); converted to TEXT in migration 062 to match the actual UI.';

COMMENT ON COLUMN public.meeting_agendas.presenter IS
  'Free-text presenter / hymn number for this agenda item. Used alongside '
  '`assigned_to` for templates that need both (e.g. Opening Hymn = '
  'hymn number in `presenter`, hymn title in `description`).';
